version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kv123
    volumes:
      - ./mongo-data:/data/db
